language: node_js

node_js:
  -8

branchs:
  only:
    -master

cache:
  directories:

before_install:
  -echo('ready install')

install:
  -npm install

scripts:
  -npm run build-only

after_success:
  -echo("test success")